### PR TITLE
fix(#40): unpipe sink on close

### PR DESCRIPTION
**Pull request by ulken**
Apart from closing the readline interface, the write sink piped to the input needs to be detached.

Fixes https://github.com/natemoo-re/clack/issues/40

### CODE REVIEW

**Comment by ulken** [comment]
Sorry, fixing a typo in the branch name automatically closed the old PR...

**Review by natemoo-re — APPROVED** [review]
Great catch, thank you so much for the PR!

**Comment by ulken** [comment]
Glad to help. For future reference: what's your policy/process for change sets? Should I have included one or not? Should all PRs come with one?

**Comment by natemoo-re** [comment]
Yeah, I love when contributors add a changeset to their own PR! You have the most context. But it's also pretty trivial to add one, so I don't mind if you'd rather leave it up to me.

**Comment by ulken** [comment]
Noted! 

Thanks for the invite — an honor 🙏

So, just to set things straight: What's the deal? What do you expect of me as a contributor?

Let me know if you'd like me to take a look at something. Review PRs or tackle some issue. I suppose "fixing" requested changes of other people's PRs wouldn't be appreciated by the authors, right? 

PS. Can I find/reach you somewhere more convenient than through PR comments? 😜 Of course, if you'd like to restrict communication to issues/PRs, that's totally fine.

**Pull request merged**
