### PR TITLE
fix(@clack/prompts): clear `spinner`'s hooks on `spinner.stop`

### PR DESCRIPTION
**Pull request by Mist3rBru**
This PR adds registration and clear steps to spinner's hooks

### CODE REVIEW

**Comment by Mist3rBru** [comment]
@mikenikles may you test this fix, I could not reproduce the error

**Comment by mikenikles** [comment]
Beautiful 😍! That works exactly as expected. I was half-way through creating a bug ticket, but I won't bother finishing that given it's already fixed.

Thanks a million 🙏!

image

**Comment by Mist3rBru** [comment]
Awesome! Thank you for report 😄.

And don't bother about creating issue reports, they are our opportunities to improve the package.

**Review by cpreston321 — APPROVED** [review]

**Comment by BryceBarbara** [comment]
@Mist3rBru  any idea when a new release will be cut? I'd really appreciate being able to use this fix as it's currently what is needed to fix my CLI.

**Comment by Mist3rBru** [comment]
Hey @BryceBarbara! This release could be managed by @cpreston321; however, it appears that he has been inactive for some time, and it's possible that he is awaiting the a return of @natemoo-re along with some other dependencies.

**Comment by cpreston321** [comment]
Hello @Mist3rBru! 

I am actually awaiting for some feedback from @natemoo-re! I haven't heard that much from him since he is full time working on Astro. 

Once he gives me the go head - I will trigger next release. I just want to make sure we are align on the merges so far.

Thanks, 
CP

**Comment by natemoo-re** [comment]
Thanks for the ping, y'all! Sorry I've been MIA. Hoping to onboard some additional maintainers soon and get back on top of things here.

**Pull request merged**
